name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Python versions
      uses: actions/setup-python@v4
      with:
        python-version: |
          3.8
          3.9
          3.10
          3.11
          3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox coveralls

    - name: Test with tox
      run: |
        python -m tox

    - name: Report to coveralls.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m coveralls --service=github
